---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default
  namespace: ingress-nginx
spec:
  secretName: default-tls
  duration: 8640h # 360d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - lab
  commonName: lab0.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - lab0.local
  uris:
    - spiffe://cluster.local/ns/ingress-nginx/sa/ingress-nginx-nginx-ingress
  ipAddresses:
    - 192.168.50.200
  issuerRef:
    name: lab-issuer
    kind: ClusterIssuer
    group: cert-manager.io
