apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab0
  namespace: ingress-nginx
  annotations:
    nginx.org/mergeable-ingress-type: master
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - lab0.local
      secretName: default-tls
  rules:
    - host: lab0.local
