apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  chart:
    spec:
      chart: nginx-ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ghcr-ingress-nginx
      version: 0.18.1
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: ingress-nginx
  values:
    controller:
      defaultTLS:
        secret: ingress-nginx/default-tls
