---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  interval: 30m
  targetNamespace: kube-prometheus-stack
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '>=50.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 30m
  values:
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
            selector: {}
      ingress:
        ingressClassName: nginx
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: lab-issuer
        hosts:
          - alertmanager.lab0.local
        paths:
          - /
        tls:
          - secretName: alertmanager-tls
            hosts:
              - alertmanager.lab0.local
    grafana:
      ingress:
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: lab-issuer
        enabled: true
        hosts:
          - grafana.lab0.local
        path: /
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.lab0.local
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
            selector: {}
      ingress:
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: lab-issuer
        enabled: true
        hosts:
          - prometheus.lab0.local
        paths:
          - /
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.lab0.local
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
