---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  interval: 30m
  targetNamespace: kube-prometheus-stack
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '>=50.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 30m
  values:
    alertmanager:
      alertmanagerSpec:
        routePrefix: /alertmanager
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
            selector: {}
      ingress:
        ingressClassName: nginx
        enabled: true
        annotations:
          nginx.org/mergeable-ingress-type: "minion"
        hosts:
          - lab0.local
        paths:
          - /alertmanager
        tls: []
    grafana:
      grafana.ini:
        server:
          domain: lab0.local
          root_url: "%(protocol)s://%(domain)s/grafana"
          serve_from_sub_path: true
      ingress:
        ingressClassName: nginx
        annotations:
          nginx.org/mergeable-ingress-type: "minion"
        enabled: true
        hosts:
          - lab0.local
        path: /grafana
        tls: []
    prometheus:
      prometheusSpec:
        routePrefix: /prometheus
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
            selector: {}
      ingress:
        ingressClassName: nginx
        annotations:
          nginx.org/mergeable-ingress-type: "minion"
        enabled: true
        hosts:
          - lab0.local
        paths:
          - /prometheus
        tls: []
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
