---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: default
spec:
  interval: 30m
  targetNamespace: cert-manager
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./charts/cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: flux-system
      interval: 30m
  values:
    installCRDs: true
