---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  interval: 30m
  targetNamespace: prometheus-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./charts/kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: flux-system
      interval: 30m
