apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-registry-pvc
  namespace: local-registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
